import { Poppins, DynaPuff } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
    variable: '--font-poppins',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['sans-serif'],
});

const dynapuff = DynaPuff({
    variable: '--font-dynapuff',
    subsets: ['cursive'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html
            lang='en'
            className={`${poppins.variable} ${dynapuff.variable} h-full antialiased`}
        >
            <body className='min-h-full flex flex-col'>{children}</body>
        </html>
    );
}
